- name: Deploy Application
  hosts: webapp
  become: yes
  tasks:
    - name: Install Require
      apt: name={{ item }} state=present
      with_items:
      - python3
      - python-setuptools
      - python-dev-is-python3
      - build-essential
      - python3-pip

    - name: Install MySQL Database
      apt: name={{ item }} state=latest
      with_items:
      - mysql-server
      - mysql-client

    - name: Start MySQL
      systemd_service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Database
      command: "{{ item }}"
      with_items:
      - mysql -e "DROP DATABASE IF EXISTS {{ database.name }}; CREATE DATABASE {{ database.name }};"
      - mysql -e "show databases;"

    - name: Install Flask Dependencies
      pip:
        name: "{{ item }}"
        state: present
      with_items:
      - flask
      - flask-mysql

    - name: Copy Source Application
      copy: src=./app.py dest=/opt/app.py

    - name: Start Application
      shell: nohup python3 /opt/app.py &
