Vagrant.configure("2") do |config|

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.network "private_network", ip: "10.10.0.#{i}", auto_config: false
    end
    
  end
  
end