- name: Deploy a web application  
  hosts: db_and_web_01,db_and_web_02
  vars:
    db_name: employee_db
    db_user: db_user
    db_passwd: passwd
  tasks:
    - name: Install and Required Dependencies
      apt: name={{ item }} state=installed
      with_items: 
      - python
      - python-setuptools
      - python-dev
      - build-essential
      - python-pip
    
    - include: task/deploy_db.yaml
    - include: task/deploy_web.yaml