- hosts: lb_haproxy
  become: true
  tasks:
  - name: Set host name
    hostname:
      name: haproxy
      use: systemd

  # - name: Disable SELinux
  #   selinux:
  #     state: disabled
  #   msg: "Config SELinux state changed to disabled"
  - name: Set Node host
    command:
      cmd: |
        cat <<EOF >> /etc/hosts
        10.10.0.1 kubernetes-haproxy
        10.10.0.10 kubernetes-master-01
        10.10.0.11 kubernetes-master-02
        10.10.0.20 kubernetes-worker-01
        EOF

  - name: Install haproxy
    apt: name=haproxy state=present
    tags: haproxy

  - name: Copy file with owner and permission, using symbolic representation
    copy:
      src: ./config/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg

  - name: Restart HAProxy
    systemd_service:
      state: restarted
      name: haproxy.service

- hosts: cluster
  tasks:
  - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
    when: kubernetes_installed is changed
  - name: Kernel module prerequesites
    command:
      cmd: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF
  - name: Set Params required setup
    command:
      cmd: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables      = 1
        net.bridge.bridge-nf-call-ip6tables     = 1
        net.ipv4.ip_forward                     = 1
        EOF
        
  - name: Set Params required setup
    command: sysctl --system
  
  - name: Install Containerd
    get_url:
    url:  https://github.com/containerd/containerd/releases/download/v1.7.13/containerd-1.7.13-linux-amd64.tar.gz
    dest: /setup