- name: Deploy application
  hosts: application_server
  tasks:
    - name: Coppy Application Code
      copy:
        src: app_code/
        dest: /opt/application
      notify: Restart Application Service
  
  handlers:
    - name: Restart Application Service
      service: 
        name: application_servicec
        state: restarted